apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fs-fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs-fe
  template:
    metadata:
      labels:
        app: fs-fe
        version: v1
    spec:
      containers:
        - name: fs-fe
          image: gcr.io/feedsense-204023/fs-fe:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: fs-fe-service
          - containerPort: 34000
            name: fs-fe-rpc


              

