apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fs-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs-fe-dep
  template:
    metadata:
      labels:
        app: fs-fe
    spec:
      containers:
        - name: fs-fe
          image: gcr.io/feedsense-204023/fs-fe:v1
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080