apiVersion: v1
kind: Service
metadata:
  name: fs-fe-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: fs-fe-service
    - port: 34000
      targetPort: fs-fe-rpc
  selector:
    name: fs-fe