apiVersion: v1
kind: Service
metadata:
  name: fs-fe-svc
  labels:
    app: fs-fe
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: fs-fe