apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fs-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs-fe
  template:
    metadata:
      labels:
        app: fs-fe
        version: v1
    spec:
      containers:
        - name: fs-fe
          image: gcr.io/feedsense-204023/fs-fe:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DEMO_ENV
              value: staging

