apiVersion: v1
kind: Service
metadata:
  name: fs-fe
  labels:
    name: fs-fe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: fs-fe