apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fs-igbot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs-igbot
  template:
    metadata:
      labels:
        app: fs-igbot
    spec:
      containers:
        - name: fs-igbot
          image: gcr.io/feedsense-204023/fs-igbot:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 30200
            name: rpc